from launch import LaunchDescription
from launch_ros.actions import Node


def generate_launch_description():
    return LaunchDescription([
        Node(
            package='turtlebot3_nav',
            executable='turtlebot_nav_sim',
            name='turtlebot_nav_sim',
            output='screen',
            parameters=[{
                'use_sim_time': True,
                'map_frame': 'map',
                'base_frame': 'base_footprint',
                'fallback_base_frame': 'base_link',
                'use_param_goal': False,
                'goal_x': 0.0,
                'goal_y': 0.0,
                'goal_tolerance': 0.15,
                'linear_speed': 0.22,
                'max_angular_speed': 1.35,
                'yaw_gain': 1.9,
                'lookahead_distance': 0.50,
                'control_frequency': 10.0,
                'replan_period': 1.0,
                'occupied_threshold': 50,
                'unknown_cost': 6.0,
                'allow_unknown': True,
                'inflation_radius': 0.16,
                'soft_inflation_radius': 0.30,
                'soft_inflation_cost': 8.0,
                'path_smoothing_enabled': True,
                'smoothing_clearance_radius': 0.18,
                'emergency_stop_dist': 0.14,
                'side_emergency_dist': 0.12,
                'rear_emergency_dist': 0.10,
                'front_angle_deg': 30.0,
                'goal_block_search_radius': 0.45,
                'map_edge_margin': 0.20,
                'frontier_candidate_limit': 50,
                'frontier_min_cluster_size': 4,
                'frontier_reached_tolerance': 0.35,
                'frontier_info_radius': 0.35,
                'frontier_goal_weight': 1.2,
                'frontier_robot_weight': 0.35,
                'frontier_info_weight': 0.12,
                'frontier_switch_margin': 0.8,
                'subgoal_commit_time': 4.0,
                'subgoal_early_release_distance': 0.55,
                'subgoal_blacklist_radius': 0.35,
                'reachable_switch_margin': 0.35,
                'reachable_visit_radius': 0.45,
                'reachable_visit_penalty': 2.0,
                'reachable_history_size': 20,
                'reachable_path_cost_weight': 0.25,
                'optimistic_planning_margin': 3.0,
                'optimistic_unknown_cost': 5.0,
                'optimistic_outside_map_cost': 8.0,
                'optimistic_max_expansions': 80000,
                'subgoal_direction_switch_angle': 0.55,
                'subgoal_large_switch_improvement': 1.20,
                'subgoal_same_direction_tolerance': 0.05,
                'local_target_switch_angle': 0.45,
                'local_target_reached_distance': 0.16,
                'local_target_path_tolerance': 0.30,
                'local_target_large_switch_improvement': 0.35,
                'rotation_debug_period': 2.0,
                'min_linear_speed_scale': 0.40,
                'curvature_speed_gain': 0.45,
                'obstacle_slow_dist': 0.45,
                'side_slow_dist': 0.24,
                'obstacle_repulsion_dist': 0.34,
                'obstacle_repulsion_gain': 0.60,
                'side_balance_gain': 0.25,
                'front_turn_gain': 0.55,
                'rotate_in_place_yaw': 1.10,
                'stuck_timeout': 4.0,
                'stuck_progress_distance': 0.08,
                'recovery_enabled': True,
                'recovery_turn_speed': 0.95,
                'recovery_turn_duration': 1.1,
                'recovery_forward_speed': 0.08,
                'recovery_forward_duration': 0.8,
                'use_scan_free_space_layer': True,
                'scan_free_space_max_range': 3.0,
                'scan_free_space_cost': 1.6,
                'scan_free_space_ray_step': 0.05,
                'scan_obstacle_endpoint_margin': 0.18,
                'publish_scan_free_space_marker': True,
                'publish_nav_augmented_map': True,
                'scan_free_space_ttl': 5.0,
            }],
        ),
    ])
